# permissions for end users to edit morpheusconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: morpheusconfig-editor-role
rules:
- apiGroups:
  - infrastructure.morpheusdata.com
  resources:
  - morpheusconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.morpheusdata.com
  resources:
  - morpheusconfigs/status
  verbs:
  - get
