# permissions for end users to edit vspheres.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vsphere-editor-role
rules:
- apiGroups:
  - infrastructure.morpheusdata.com
  resources:
  - vsphereinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.morpheusdata.com
  resources:
  - vsphereinstances/status
  verbs:
  - get
