# permissions for end users to view vspheres.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vsphere-viewer-role
rules:
- apiGroups:
  - infrastructure.morpheusdata.com
  resources:
  - vsphereinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.morpheusdata.com
  resources:
  - vsphereinstances/status
  verbs:
  - get
